### ISSUE TITLE
Efficiency of DC/DC with many points

### ISSUE THREAD

**Issue by guillaumezin** [smariel/PTree#10]
Hi,

It would be great to support more than one efficiency point for DC/DC, for instance:
- 90% at 2A
- 70% at 1A
- 65% at 500mA

And to calculate between points using linear interpolation. 4 or 5 points would be enough.

Thanks.

Guillaume

**Comment by smariel** [comment]
Coded in 30f3546, available in the next version.
Little form to add a point on the graph.
Click on a point to delete it.
Should be compatible with the older versions.

Rules:
- 1 point by default, 90% @ 1A (= 90% @ any A)
- if no point, 100% @ any A
- if Amps < lowest point, the lowest point is used
- if Amps > highest point, the highst point is used 
- if Amps between two points, linear interpolation (y=ax+b)

![capture d ecran 2018-05-02 a 13 07 05](https://user-images.githubusercontent.com/3503851/39520314-70210e6e-4e0a-11e8-83f5-4649a6cba04e.png)

**Comment by smariel** [comment]
Available in release [v1.1.0](https://github.com/smariel/PTree/releases/tag/v1.1.0)
