### ISSUE TITLE
Active the Column Order editing in PartList windows

### ISSUE THREAD

**Issue by davidbiteghethales19** [smariel/PTree#64]
We cannot custom the order the Columns of the Loads
in the Partlist Windows

We need to be able to change the order of the columns

**Comment by smariel** [comment]
The enhancement is relevant but require lots of works. It may be added in a future major release.

**Comment by smariel** [comment]
I added a contextual menu (right click) with the possibility to move a part before an other one. It will be available in the next realease. Does that correspond with what you had in mind ?
![Capture d’écran 2019-11-11 à 19 43 08](https://user-images.githubusercontent.com/3503851/68611913-8a113380-04bb-11ea-8070-be4adf8640c3.png)
