### ISSUE TITLE
Excel sync bug

### ISSUE THREAD

**Issue by davidbiteghethales19** [smariel/PTree#67]
If the excel file is Open, the Refresh button does not works.

Can you improve that feature?

**Comment by smariel** [comment]
Problem is hard to reproduce. It seems to work well with Open Office on Linux and macOS.

**Comment by smariel** [comment]
The problem with excel was never reproduced on my different computers and OS.

But there was a bug forcing to click two times on the Sync button to refresh the tree data. This will be fixed in the next version (v2.0.0).

Feel free to reopen an issue if it is not properly fixed on the next release.
