### ISSUE TITLE
Crash upon exiting "item edition" window with Return key

### ISSUE THREAD

**Issue by dracorpg** [smariel/PTree#94]
PTree 2.0 process terminates within one second upon closing the "Item edition" window by pressing the return/enter key when the cursor is in a field. This is, of course, extremely frustrating when trying to quickly adjust the value of a property :)
Changes made in the "Item edition" window are applied and can be seen reflected in the main window in the split second before the app crashes.

**To Reproduce**
1. Open an existing PTree file (e.g. `example.ptree`) or create a new one and add at least a source to have something to edit
2. Double-click an item (source / regulator / load) to open its edition window
3. Click in any property field (changing its value is optional)
4. Press the return key
5. If the app doesn't crash almost instantly, repeat steps 2-4 a few times (I couldn't pinpoint what makes it crash vs. not crash, but it does happen a lot)

**Expected behavior**
No crash, of course!

**Desktop (please complete the following information):**
 - OS: Windows (also confirmed on Fedora)
 - Version: 2.0 (regression from 1.8)

**Comment by smariel** [comment]
Can't reproduce on macOS.
Also happens with ESCAPE.
Only happens with the keyboard, not the buttons.

It may be the default behavior of using keys to validate/cancel a form with the new version of Chromium (on Windows and Linux), interfering with the app process.
To be tested : add `event.preventDefault()` after triggering ENTER and ESCAPE in the event callback.
https://github.com/smariel/PTree/blob/2bffeb484f43b80a7dfd1d725604386ed1a55e17/js/class.ItemEditor.js#L469
