### ISSUE TITLE
Export image as PNG

### ISSUE THREAD

**Issue by dracorpg** [smariel/PTree#95]
**Is your feature request related to a problem? Please describe.**
The "export image" feature currently generates a JPEG image.
This format was developed for photographs and is unsuited to PTree's kind of technical graphics (sharp uniform-color shapes) which get muddied by JPG's DCT-based compression.

**Describe the solution you'd like**
Image should instead be exported as PNG, which is the raster format of choice for such graphics.
A very rough test (using a screenshot...) shows ~2x smaller file size - plus PNG compression is lossless.

Change should be trivial as [HTMLCanvasElement.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) (rightfully) defaults to PNG, so it's just a matter of removing the 2 last arguments on the final line below:
https://github.com/smariel/PTree/blob/71619af65f3f759815c4694f6ca0d28a756b1ea2/js/class.Canvas.js#L784-L796

I guess the `toJPEGdataURL` method should also be renamed then ;)

I'm open to submitting a PR if you feel that helps (although it should be a super small change so I somehow doubt it does)

**Comment by smariel** [comment]
JPEG was used on purpose to avoid Alpha. But it doesn't seems necessary anymore.
This has to be changed in all export functions.

Thanks.
